app/authentication/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin

from app import db, login_manager


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)

    def __repr__(self):
        return self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255), nullable=False, unique=True, index=True)
    password_hash = db.Column(db.String(255))
    created_at = db.Column(db.DateTime(), default=datetime.utcnow)

    def __repr__(self):
        return self.username

    @property
    def password(self):
        raise AttributeError('Password is not readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Extra(db.Model):
    __tablename__ = 'extras'
    id = db.Column(db.Integer, primary_key=True)
    attr = db.Column(db.String(30))
    string_value = db.Column(db.String(255))
    integer_value = db.Column(db.Integer)
    date_value = db.Column(db.DateTime())

app/authentication/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length, Email, EqualTo


class RegisterForm(Form):
    name = StringField('Full Name', validators=[Required(), Length(1, 255)])
    email = StringField('Email',
        validators=[Required(), Length(1, 255), Email()])
    username = StringField('User Name', validators=[Required(), Length(1, 64)])
    password = PasswordField('Password', validators=[
                Required(), EqualTo('password2', message='Passwords must match')
    ])
    password2 = PasswordField('Confirm password', validators=[Required()])


class LoginForm(Form):
    username = StringField('User Name', validators=[Required(), Length(1, 64)])
    password = PasswordField('Password', validators=[Required()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Sign In')

app/__init__.py
from flask import Flask, render_template

from flask.ext.moment import Moment
from flask.ext.mail import Mail
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

from config import config


moment = Moment()
mail = Mail()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'authentication.login'

from app.authentication import models

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    config[config_name].init_app(app)

    # register extensions

    moment.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # register blueprints

    from authentication import authentication as authentication_blueprint
    app.register_blueprint(authentication_blueprint)

    from customers import customers as customers_blueprint
    app.register_blueprint(customers_blueprint)

    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from orders import orders as orders_blueprint
    app.register_blueprint(orders_blueprint)

    from resturants import resturants as resturants_blueprint
    app.register_blueprint(resturants_blueprint)

    return app

app/authentication/__init__.py
from flask import Blueprint

authentication = Blueprint('authentication', __name__)

from . import views

app/authentication/views.py
from flask import render_template, redirect, url_for, flash, request
from app import db
from . import authentication

from .forms import LoginForm, RegisterForm
from .models import User
from flask.ext.login import (
    login_user,
    current_user,
    login_required,
    logout_user
    )


@authentication.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if request.method == 'POST':
        password = form.password.data
        username = form.username.data
        user = User.query.filter_by(username=username).first()
        if user is not None and user.verify_password(password) == True:
            login_user(user, form.remember_me.data)
            flash('Welcome to Sauce')
            return redirect(url_for('authentication.index'))
        flash('Invalid Username or Password!')
        return redirect(url_for('authentication.login'))
    return render_template('authentication/login.html', form=form)


@authentication.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        user = User()
        user.username = form.username.data
        user.name = form.name.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash('You are registerd!')
        return redirect(url_for('main.index'))
    return render_template('authentication/register.html', form=form)


@authentication.route('/logout', methods=['GET'])
def logout():
    logout_user()
    flash('You have logged out!')
    return redirect(url_for('authentication.login'))

app/customers/__init__.py
from flask import Blueprint

customers = Blueprint('customers', __name__)

from . import views

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template
from . import main


@main.route('/', methods=['GET'])
def index():
    return render_template('main/index.html')


@main.route('/about', methods=['GET'])
def about():
    return render_template('main/about.html')


@main.route('/contact/', methods=['GET'])
def contact():
    return render_template('main/contact.html')

app/orders/__init__.py
from flask import Blueprint

orders = Blueprint('orders', __name__)

from . import views

app/resturants/__init__.py
from flask import Blueprint

resturants = Blueprint('resturants', __name__)

from . import views

app/templates/authentication/login.html
{% extends "base.html" %}
{% block body %}
{{ super() }}
<div class="container">
    <div class="row">
        <div class="span12">
          <form class="form-horizontal" action='{{ url_for('authentication.login') }}' method="POST">
            {{ form.hidden_tag() }}
                <fieldset>
                    <div id="legend">
                        <legend class="">Login</legend>
                    </div>
                    <div class="control-group">
                        <!-- Username -->
                        <label class="control-label"  for="username">{{ form.username.label }}</label>
                        <div class="controls">
                          {{ form.username }}
                        </div>
                    </div>
                    <div class="control-group">
                        <!-- Password-->
                        <label class="control-label" for="password">{{ form.password.label }}</label>
                        <div class="controls">
                              {{ form.password }}
                        </div>
                    </div>
                    {{ form.remember_me }} {{ form.remember_me.label }}
                    <div class="control-group">
                        <!-- Button -->
                        <div class="controls">
                            <p><input type="submit" value="Sign In"></p>
                        </div>
                    </div>
              </fieldset>
            </form>
        </div>
      </div>
</div>
{% endblock %}

app/templates/authentication/register.html
{% extends 'base.html' %}
{% block body %}
{{ super() }}
<div class="container">
<form class="form-horizontal" method='post' action={{ url_for('authentication.register') }}>
<div class="container">
    <form class="form-horizontal" role="form">
      <div id="legend">
        <legend class=""><h2>Registration</h2></legend>
      </div>
        <div class="form-group">
            <label for="name" class="col-sm-3 control-label">Full Name</label>
            <div class="col-sm-9">
                {{ form.name }}
                <span class="help-block">Full Name, Name, eg.: Will Smith, Tim Harry</span>
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-sm-3 control-label">Email</label>
            <div class="col-sm-9">
              {{ form.email }}
            </div>
        </div>
        <div class="form-group">
            <label for="username" class="col-sm-3 control-label">User Name</label>
            <div class="col-sm-9">
                {{ form.username }}
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-sm-3 control-label">Password</label>
            <div class="col-sm-9">
              {{ form.password }}
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-sm-3 control-label">Password Confirmaiton</label>
            <div class="col-sm-9">
              {{ form.password2 }}
            </div>
        </div>
        </div> <!-- /.form-group -->
        <div class="form-group">
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <div class="checkbox">
                    <label>
                        <input type="checkbox">I accept <a href="#">terms</a>
                    </label>
                </div>
            </div>
        </div> <!-- /.form-group -->
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <button type="submit" class="btn btn-primary btn-block">Register</button>
            </div>
        </div>
    </form> <!-- /form -->
</div> <!-- ./container -->
</form>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
       <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Sauce Food Delievery</title>
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        {% block body %}
        {% include 'includes/_navbar.html' %}
            <div class="container">
            {% for message in get_flashed_messages() %}
                  <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        {{ message }}
                        <button class="pull-right" type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        <span aria-hidden="true">&times;</span>
                        </button>
                  </div>
            {% endfor %}
            </div>
        {% endblock %}

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/includes/_flash.html
<div class="container">
{% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert"></button>
            {{ message }}
      </div>
{% endfor %}
</div>

app/templates/includes/_navbar.html
<!-- Static navbar -->
      <nav class="navbar navbar-default">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{{ url_for('main.index') }}">Sauce</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                      <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
                      <li><a href="{{ url_for('main.about') }}">About</a></li>
                      <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                              <li><a href="#">Food Delivery</a></li>
                              <li><a href="#">Food Reciepes</a></li>
                              <li role="separator" class="divider"></li>
                              <li class="dropdown-header">Reservations</li>
                              <li><a href="#">Restaurants Reservations</a></li>
                              <li><a href="#">Event Catering</a></li>
                          </ul>
                       </li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                      <li><a href="{{ url_for('authentication.logout') }}">Logout</a></li>
                      {% else %}
                      <li><a href="{{ url_for('authentication.register') }}">Register</a></li>
                      <li><a href="{{ url_for('authentication.login') }}">Login</a></li>
                  {% endif %}
                  </ul>
              </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
</nav>

app/templates/main/about.html
{% extends 'base.html' %}
{% block body %}
{{ super() }}
about
{% endblock %}

app/templates/main/contact.html
{% extends 'base.html' %}
{% block body %}
{{ super() }}
contact
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% block body %}
{{ super() }}
hello world! template setup
{% endblock %}